language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack:
    secure: travisciespacio:rQdcnN1UDyL8qe05V0oB1DTw
  email:
      recipients:
        - kanasir@hotmail.com
      on_success: always
      on_failure: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 2bc6876c-dfa0-4752-9984-bf31fae55754
  app: platzi-store-backend-khalil
  on:
    repo: KhalilKAN/platzi-store-backend